### ISSUE TITLE
no textures in some places of the map

### ISSUE THREAD

**Issue by Dante-Royal** [Waterdish/Shipwright-Android#91]
Epona, the hyrule castle and others have no textures and look invisible.

**Comment by J-Rios** [comment]
This is caused due assets update was missing at 9.0.2 release, it was fixed in 9.0.2-Patch1 release.

**Comment by Dante-Royal** [comment]
I did everything you told me to do, and I still can't see the textures. I suppose I'll have to stay with version 1.3.0

**Comment by SharpSPUD** [comment]
I got the same problem, missing textures in Epona, Kokiri forest's sky, Hyrule castle (outside and inside), just to name the first places you visit in the game.

Tested versions: 
v9.0.2
v9.0.2 Patch 1
v9.0.2 Patch 2

All three have the textures missing problems with any rom.

Finally, I tested v1.0.3 with pal v1.0 rom and doesn't show any texture problem, so I'll stick with that for now.

![Image](https://github.com/user-attachments/assets/727fa668-2db1-4958-b64b-26e02977510f)
![Image](https://github.com/user-attachments/assets/440cc462-63dd-4b9b-9a83-adfd05c1e246)
![Image](https://github.com/user-attachments/assets/4955f2c4-5ad3-4233-881d-eee5cd539c23)
![Image](https://github.com/user-attachments/assets/9bbc0b99-64b9-4cd8-9acc-e527a4e88174)
